steps:
  - label: 'Tests'
    command: "mvn clean test"
    agents:
    - "contaboagent=true"
  - label: 'Deploy Sonar'
    command: "mvn clean deploy sonar:sonar"

  - label: "Sonar Analysis"
    command: 'scripts/sonarqube.sh'
