steps:
  - label: 'Tests'
    command: "mvn clean test"
    agents:
      - "contaboagent=true"

  - wait

  - label: "Sonar Analysis"
    command: 'scripts/sonarqube.sh'
    agents:
      - "contaboagent=true"
